services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: moovly_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-defaultpassword} # Valeur par défaut
      POSTGRES_DB: moovlydb
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U moovly_user"]
      interval: 5s

  app:
    build:
      context: . # Racine du projet
      dockerfile: server/Dockerfile # Chemin relatif correct
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/moovlydb
      DATABASE_USERNAME: moovly_user
      DATABASE_PASSWORD: ${DB_PASSWORD:-defaultpassword}
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:

