server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: projet-ioe

  datasource:
    url: jdbc:postgresql://localhost:5432/moovlydb
    username: postgres
    password: Fello2020@

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
