server:
  port: ${PORT:8080}  # Railway injecte automatiquement $PORT

spring:
  datasource:
    url: ${DATABASE_URL}  # Railway fournira cette variable
    hikari:
      maximum-pool-size: 3  # Limité en version gratuite
