server:
  port: 8081
  servlet:
    #application context
    context-path: /api

spring:
  application:
    name: projet-ioe

  datasource:
    url: jdbc:postgresql://localhost:5432/Yourdb
    username: yourUserName
    password: YourPasseWord
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  hibernate:
    dialect=org:
      hibernate:
        spatial:
          dialect:
            PostgisDialect:

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
